comment:
    resource: "@CommentBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
api:
    resource: '.'
    type: 'api_platform'
    prefix: '/api' # Optional
